name: Jest tests for bestofjs-webui

on:
  push:
    paths:
      - "apps/bestofjs-webui/src/**"
  pull_request:
    paths:
      - "apps/bestofjs-webui/src/**"
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        # `setup-node` already caches npm
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install -F bestofjs-webui --no-hoist
      - name: Run Jest tests
        run: pnpm -F bestofjs-webui run test:ci
